### ISSUE TITLE
Missing .p file

### ISSUE THREAD

**Issue by CaptainEmerson** [sophieball/toxicity-detector#18]
```
(myproject) emersonm@emersonm:~/toxicity-detector$ bazel run //main:train_classifier_g
INFO: Analyzed target //main:train_classifier_g (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //main:train_classifier_g up-to-date:
  bazel-bin/main/train_classifier_g
INFO: Elapsed time: 0.231s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
not found
⚠ Skipping model package dependencies and setting `--no-deps`. You
don't seem to have the spaCy package itself installed (maybe because you've
built from source?), so installing the model dependencies would cause spaCy to
be downloaded, which probably isn't what you want. If the model package has
other dependencies, you'll have to install them manually.
Collecting en_core_web_sm==2.2.5
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz (12.0 MB)
     |████████████████████████████████| 12.0 MB 782 kB/s 
Building wheels for collected packages: en-core-web-sm
  Building wheel for en-core-web-sm (setup.py) ... done
  Created wheel for en-core-web-sm: filename=en_core_web_sm-2.2.5-py3-none-any.whl size=12011738 sha256=e0e3d1da5c84ddc3e10c713583df83f2a959cc2959d9fe40611aa1c0e5be2cf3
  Stored in directory: /tmp/pip-ephem-wheel-cache-8ruqo_iq/wheels/51/19/da/a3885266a3c241aff0ad2eb674ae058fd34a4870fef1c0a5a0
Successfully built en-core-web-sm
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-2.2.5
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/usr/local/google/home/emersonm/myproject/lib/python3.7/site-packages/en_core_web_sm
-->
(myproject) emersonm@emersonm:~/toxicity-detector$ bazel run //main:train_classifier_g
INFO: Analyzed target //main:train_classifier_g (72 packages loaded, 9282 targets configured).
INFO: Found 1 target...
Target //main:train_classifier_g up-to-date:
  bazel-bin/main/train_classifier_g
INFO: Elapsed time: 3.003s, Critical Path: 0.58s
INFO: 0 processes.
INFO: Build completed successfully, 5 total actions
INFO: Build completed successfully, 5 total actions
not found
⚠ Skipping model package dependencies and setting `--no-deps`. You
don't seem to have the spaCy package itself installed (maybe because you've
built from source?), so installing the model dependencies would cause spaCy to
be downloaded, which probably isn't what you want. If the model package has
other dependencies, you'll have to install them manually.
Requirement already satisfied: en_core_web_sm==2.2.5 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz#egg=en_core_web_sm==2.2.5 in /usr/local/google/home/emersonm/myproject/lib/python3.7/site-packages (2.2.5)
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/usr/local/google/home/emersonm/myproject/lib/python3.7/site-packages/en_core_web_sm
-->
/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/main/train_classifier_g.runfiles/deps_pypi__spacy_2_2_4/spacy/data/en
You can now load the model via spacy.load('en')
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/main/train_classifier_g.runfiles/__main__/main/train_classifier_g.py", line 7, in <module>
    from src import suite
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/main/train_classifier_g.runfiles/__main__/src/suite.py", line 112, in <module>
    counter = pickle.load(open("src/pickles/github_words.p", "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'src/pickles/github_words.p'
(myproject) emersonm@emersonm:~/toxicity-detector$ ls -la src/pickles/
```

**Comment by CaptainEmerson** [comment]
It may be that the .p values are not specified as a [data dependency](https://docs.bazel.build/versions/master/build-ref.html#data)

**Comment by sophieball** [comment]
Added. Does it run correctly now?

**Comment by CaptainEmerson** [comment]
Yup, it appears so.
