### ISSUE TITLE
Can't find any data labeled as 1 in G's dataset

### ISSUE THREAD

**Issue by sophieball** [sophieball/toxicity-detector#27]
The support in the f-score matrix is 0

**Comment by sophieball** [comment]
In PR #32, I added some code that will output the description of `perspective_score` and `politeness_score` to the log.

**Comment by sophieball** [comment]
@CaptainEmerson After you run the new code with G's data, can you report the description of `perspective score` and `stanford polite` in the logging file?

**Comment by CaptainEmerson** [comment]
https://docs.google.com/document/d/1dPfZD89molxMU--QlPYKTqUGyuJBniiSYSQFfgIPKn8/edit

**Comment by sophieball** [comment]
#37 
@CaptainEmerson, I've added more outputs in the code. Can you run it and report the output in the log?

**Comment by CaptainEmerson** [comment]
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__pandas_1_0_5/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'raw_prediction'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/main/train_classifier_g.py", line 69, in <module>
    train_model(training, unlabeled)
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/main/train_classifier_g.py", line 42, in train_model
    model = s.self_issue_classification_all()
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/suite.py", line 548, in self_issue_classification_all
    self_issue_classification_statistics_per, matched_pairs=matched_pairs)
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/suite.py", line 528, in all_combinations
    s = function()
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/suite.py", line 538, in self_issue_classification_statistics_per
    self.self_issue_classification_from_comments()
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/suite.py", line 504, in self_issue_classification_from_comments
    self.train_data = self.cross_validate_classify()
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/suite.py", line 479, in cross_validate_classify
    data["raw_prediction"].tolist())))
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__pandas_1_0_5/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__pandas_1_0_5/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'raw_prediction'

**Comment by sophieball** [comment]
@CaptainEmerson In the new output (assuming you run the whole thing, training+predicting), you should be able to find some descriptive stats of training True, training False, unlabeled True, unlabeled False. 

I've also added the number of True prediction produced by the model itself (called `raw prediction`). Hopefully this number is not zero. Then there are the number of comments that are initially predicted as True by the model, but later turn out to be due to SE words, and the number of comments that are initially True but turn out to be angry at themselves.

**Comment by CaptainEmerson** [comment]
not found
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/main/train_classifier_g.py", line 114, in <module>
    predict_unlabeled(unlabeled_data, trained_model)
NameError: name 'unlabeled_data' is not defined

**Comment by sophieball** [comment]
oh.. I clearly remember fixing this bug.. maybe it got overwritten when I was trying to squash the commits. I've made a new PR for this. #42

**Comment by CaptainEmerson** [comment]
https://docs.google.com/document/d/1s_ZFYdExlTEwW51snKyqSTanAi6OqESLqeEKneVkTwU/edit

**Comment by CaptainEmerson** [comment]
Using the updated data set with ~1000 training and ~1000 testing, I get:

```
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__pandas_1_0_5/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/main/train_classifier_g.py", line 112, in <module>
    [training, unlabeled] = receive_data.receive_data()
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/receive_data.py", line 16, in receive_data
    data["_id"] = data["_id"].apply(str)
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__pandas_1_0_5/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__pandas_1_0_5/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '_id'
```

The only difference I can think of is that the new testing data set has all NAs for the second, isHighPushback column. But that seems unrelated to the id.

**Comment by CaptainEmerson** [comment]
Oops, I accidentally fed in the wrong column names.

**Comment by CaptainEmerson** [comment]
Updated results:
https://docs.google.com/document/d/1f9SYGDhu6f_AfEdcAb0mMbEMlkquUcy_xxcwjDsl-MA/edit

**Comment by sophieball** [comment]
Hmm.. so still no 1. Only using these two features won't work.. I'm experimenting with more features now

**Comment by sophieball** [comment]
I'm closing this issue: it's opened for a while; the conversation is too long to scroll to the newest comment quickly; the problem is not solved but we are currently trying other stuff to solve this problem -> I'll open new issues for more specif problems.
